context:
  version: ${{ env.get("PKG_VERSION") }}

package:
  name: toksearch
  version: ${{ version }}

source:
  path: ..

build:
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.20, <2
    - openblas
  run:
    - python
    - mdsplus-xrdcl >=0.2.2
    - numpy >=1.20, <2
    - pymssql
    - ray-core
    - pyspark >=4
    - scipy
    - sh
    - xarray
    - bottleneck
    - openblas
    - joblib >=1.3
    - jupyter
    - fsspec
    - zarr =3

tests:
  - script:
      content:
        - cd tests && ./testit
    requirements:
      run:
        - openjdk >=17
    files:
      source:
        - tests/

about:
  homepage: https://github.com/GA-FDP/toksearch
  license: Apache-2.0
  license_file: LICENSE
  summary: Data pipeline framework for fusion experimental data
  repository: https://github.com/GA-FDP/toksearch

extra:
  recipe-maintainers:
    - sammuli
