#!/usr/bin/env python

# Copyright 2024 General Atomics
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import os
import argparse
import yaml

from sh import sbatch, salloc
import subprocess

from toksearch.slurm.runner import SlurmRunner

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    
    SlurmRunner.update_parser(parser)

    parser.add_argument('script',
                        help='User-provided script')
    parser.add_argument('script_args',
                        help='Arguments/options for user-provided script',
                        nargs='*')

    args = parser.parse_args()

    slurm_runner = SlurmRunner(args.num_nodes, config_file=args.config_file)

    if args.batch:
        sys.exit(slurm_runner.run_batch(args.script, *args.script_args).returncode)
    else:
        sys.exit(slurm_runner.run_interactive(args.script, *args.script_args).returncode)
